import { Color, Mesh, Program, Renderer, Triangle } from 'ogl';
import { useEffect, useRef } from 'react';
import './Strands.css';

const MAX_STRANDS = 12; const MAX_COLORS = 8;
const vert = `#version 300 es
in vec2 position; void main(){gl_Position=vec4(position,0.,1.);}`;
const frag = `#version 300 es
precision highp float; uniform float uTime; uniform vec2 uResolution; uniform vec3 uColors[${MAX_COLORS}]; uniform int uColorCount; uniform int uStrandCount; uniform float uSpeed,uAmplitude,uWaviness,uThickness,uGlow,uTaper,uSpread,uHueShift,uIntensity,uOpacity,uScale,uSaturation; out vec4 fragColor; const float PI=3.14159265;
vec3 spectrum(float t){return .5+.5*cos(2.*PI*(t+vec3(0.,.33,.67)));}
vec3 palette(float t){t=fract(t);float s=t*float(uColorCount);int i=int(floor(s));int n=i+1;if(n>=uColorCount)n=0;return mix(uColors[i],uColors[n],fract(s));}
void main(){vec2 uv=(gl_FragCoord.xy-.5*uResolution)/uResolution.y;uv/=max(uScale,.0001);float e=.06+uIntensity*.94;float env=pow(max(cos(uv.x*PI*1.3),0.),uTaper);vec3 col=vec3(0.);for(int i=0;i<${MAX_STRANDS};i++){if(i>=uStrandCount)break;float fi=float(i);float ph=fi*1.7*uSpread;float f=(2.+fi*.35)*uWaviness;float s=1.4+fi*1.2;float t=uTime*uSpeed;float w=sin(uv.x*f+t*s+ph)*.6+sin(uv.x*f*1.1-t*s*.7+ph*1.7)*.4;float y=w*(.1+.02*e)*env*uAmplitude;float thick=(.001+.05*e)*(.35+env)*uThickness;float g=thick/(abs(uv.y-y)+thick*.45);g*=g;float h=fi/float(uStrandCount)+uv.x*.3+uTime*.04+uHueShift;col+=(uColorCount>0?palette(h):spectrum(h))*g*env;}col*=.45+.7*e;col=1.-exp(-col*uGlow);float gray=dot(col,vec3(.2126,.7152,.0722));col=max(mix(vec3(gray),col,uSaturation),0.);float alpha=clamp(max(max(col.r,col.g),col.b),0.,1.)*uOpacity;fragColor=vec4(col*uOpacity,alpha);}`;
const palette = colors => { const source = colors?.length ? colors : ['#FF4242','#7C3AED','#06B6D4','#EAB308']; return Array.from({length:MAX_COLORS},(_,i)=>{const c=new Color(source[i]??source[source.length-1]);return [c.r,c.g,c.b];}); };
export default function Strands({ colors=['#F97316','#7C3AED','#06B6D4'],count=3,speed=.5,amplitude=1,waviness=1,thickness=.7,glow=2.6,taper=3,spread=1,hueShift=0,intensity=.6,saturation=1.5,opacity=1,scale=1.5,className='',style }) { const root=useRef(null); const props=useRef({}); props.current={colors,count,speed,amplitude,waviness,thickness,glow,taper,spread,hueShift,intensity,saturation,opacity,scale}; useEffect(()=>{const node=root.current;if(!node)return;const renderer=new Renderer({alpha:true,premultipliedAlpha:true,antialias:true});const gl=renderer.gl;gl.clearColor(0,0,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);const geometry=new Triangle(gl);if(geometry.attributes.uv)delete geometry.attributes.uv;const program=new Program(gl,{vertex:vert,fragment:frag,uniforms:{uTime:{value:0},uResolution:{value:[node.offsetWidth,node.offsetHeight]},uColors:{value:palette(colors)},uColorCount:{value:Math.min(colors.length,MAX_COLORS)},uStrandCount:{value:count},uSpeed:{value:speed},uAmplitude:{value:amplitude},uWaviness:{value:waviness},uThickness:{value:thickness},uGlow:{value:glow},uTaper:{value:taper},uSpread:{value:spread},uHueShift:{value:hueShift},uIntensity:{value:intensity},uOpacity:{value:opacity},uScale:{value:scale},uSaturation:{value:saturation}}});const mesh=new Mesh(gl,{geometry,program});node.appendChild(gl.canvas);const resize=()=>{renderer.setSize(node.offsetWidth,node.offsetHeight);program.uniforms.uResolution.value=[node.offsetWidth,node.offsetHeight];};window.addEventListener('resize',resize);resize();let frame;const draw=time=>{frame=requestAnimationFrame(draw);const p=props.current;Object.assign(program.uniforms,{uTime:{value:time*.001},uColors:{value:palette(p.colors)},uColorCount:{value:Math.min(p.colors.length,MAX_COLORS)},uStrandCount:{value:Math.min(Math.max(Math.round(p.count),1),MAX_STRANDS)},uSpeed:{value:p.speed},uAmplitude:{value:p.amplitude},uWaviness:{value:p.waviness},uThickness:{value:p.thickness},uGlow:{value:p.glow},uTaper:{value:p.taper},uSpread:{value:p.spread},uHueShift:{value:p.hueShift},uIntensity:{value:p.intensity},uOpacity:{value:p.opacity},uScale:{value:p.scale},uSaturation:{value:p.saturation}});renderer.render({scene:mesh});};frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);window.removeEventListener('resize',resize);gl.canvas.remove();gl.getExtension('WEBGL_lose_context')?.loseContext();};},[]);return <div ref={root} className={`strands-container ${className}`} style={style}/>; }
