import { useEffect, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';

type Agent = { agent_id: string; name: string; role: string; department: string };
const flowRoles = ['CEO', 'Project Manager', 'Designer', 'Engineer', 'QA'];
const ideas = ['Build a Netflix-style streaming platform', 'Create an AI expense tracker', 'Launch a food delivery marketplace'];

export function ProjectPlanningPage() {
  const [idea, setIdea] = useState(''); const [plan, setPlan] = useState<any>();
  const [agents, setAgents] = useState<Agent[]>([]); const [events, setEvents] = useState<any[]>([]); const [loading, setLoading] = useState(false); const [showFlow, setShowFlow] = useState(false); const [completedStep, setCompletedStep] = useState(-1); const navigate = useNavigate();
  const refresh = async (projectId: string) => { const [project, agentResponse, eventResponse] = await Promise.all([api.get(`/projects/${projectId}`), api.get('/agents'), api.get('/events')]); setPlan(project.data); setAgents(agentResponse.data); setEvents(eventResponse.data.filter((event: any) => event.payload?.project_id === projectId)); };
  useEffect(() => { if (!plan?.project_id) return; const id = plan.project_id; const socket = new WebSocket((import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000/api/v1').replace(/^http/, 'ws') + '/ws/activity'); socket.onmessage = () => refresh(id); const initial = window.setTimeout(() => refresh(id), 350); const poll = window.setInterval(() => refresh(id), 1200); return () => { window.clearTimeout(initial); window.clearInterval(poll); socket.close(); }; }, [plan?.project_id]);
  useEffect(() => { if (!plan || plan.status !== 'ready' || completedStep >= flowRoles.length) return; const timer = window.setTimeout(() => setCompletedStep(step => step + 1), 650); return () => window.clearTimeout(timer); }, [plan?.status, completedStep]);
  useEffect(() => { if (!plan?.project_id || completedStep !== flowRoles.length) return; const timer = window.setTimeout(() => navigate(`/projects/${plan.project_id}`), 1400); return () => window.clearTimeout(timer); }, [completedStep, plan?.project_id, navigate]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (idea.trim().length < 10) return; setLoading(true); setShowFlow(false); setCompletedStep(-1); try { const result = await api.post('/projects/plan', { idea }); setPlan(result.data); setEvents([]); const agentResponse = await api.get('/agents'); setAgents(agentResponse.data); window.setTimeout(() => setShowFlow(true), 900); } finally { setLoading(false); } };
  const agentFor = (role: string) => agents.find(agent => agent.role === role);
  const eventFor = (agent?: Agent) => events.find(event => event.source === agent?.agent_id);
  const output = (role: string, event: any) => { if (role === 'CEO' && plan?.strategy) return plan.strategy.executive_summary; if (role === 'Project Manager' && plan?.timeline) return `Produced ${plan.epics.length} epics, ${plan.tasks.length} tasks, and ${plan.timeline.sprints.length} milestones.`; if (event?.payload?.work_output?.outcome) return `Completed project-context review: ${event.payload.work_output.outcome}.`; return 'Project context received; analysis is queued.'; };
  const ready = plan?.status === 'ready';
  return <main className="chat-studio">
    {!plan && <section className="chat-welcome"><div className="chat-welcome-copy"><p className="chat-greeting">Welcome to CrewOS</p><h1>Your AI company is ready. <span>What will we build?</span></h1><p>Describe a product outcome and the company will organize the strategy, roadmap, architecture, and delivery plan.</p></div><form onSubmit={submit} className="chat-composer"><textarea autoFocus required minLength={10} value={idea} onChange={event => setIdea(event.target.value)} placeholder="Describe the product you want your company to build…"/><div className="composer-footer"><div className="composer-tools"><span className="tool-plus">+</span><span>Product planning</span><span className="tool-dot">•</span><span>Autonomous team</span></div><button aria-label="Send project idea" disabled={loading} type="submit">{loading ? <span className="send-loading" /> : '↗'}</button></div></form><div className="prompt-row"><span>Try an idea</span>{ideas.map(example => <button key={example} type="button" onClick={() => setIdea(example)}>{example}</button>)}</div></section>}
    {plan && !showFlow && <div className="company-loader"><span/><b>Activating company departments…</b><p>Preparing the project workspace and agent graph.</p></div>}
    {plan && showFlow && <section className="work-flow"><div className="flow-head"><div><p className="eyebrow">Live Company Workflow</p><h2>{plan.name}</h2></div><span className="project-status">{plan.status}</span></div><div className="flow-lane">{flowRoles.map((role, index) => { const agent = agentFor(role); const event = eventFor(agent); const complete = completedStep >= index || (completedStep < 0 && Boolean(event)); return <div className="flow-step" key={role}><article className={complete ? 'complete' : ''}><div className="step-number">{index + 1}</div><div className="flow-avatar">{agent?.name?.slice(0, 1) || role.slice(0, 1)}</div><b>{agent?.name || role}</b><span>{agent?.department || 'Company'}</span><p>{output(role, event)}</p><em>{complete ? 'Work recorded' : plan.status === 'strategizing' ? 'Working' : 'Waiting'}</em></article>{index < flowRoles.length - 1 && <i className={complete ? 'connector done' : 'connector'}/>}</div>; })}</div>{ready ? <><section className="final-output"><div><p className="eyebrow">Final Company Output</p><h2>{plan.strategy.executive_summary}</h2><p>{plan.timeline.delivery_forecast}</p></div><div className="output-stats"><span><b>{plan.epics.length}</b> epics</span><span><b>{plan.tasks.length}</b> tasks</span><span><b>{plan.timeline.sprints.length}</b> sprints</span></div></section><section className="plan-preview"><article><h3>Vision</h3><p>{plan.strategy.vision}</p></article><article><h3>Roadmap</h3>{plan.epics.map((epic: any) => <p key={epic.epic_id}>{epic.title}</p>)}</article><article><h3>Activity</h3>{events.slice(-6).reverse().map((event: any) => <p key={event.event_id}>{event.type.replaceAll('_', ' ').toLowerCase()}</p>)}</article></section></> : <div className="planning-progress"><span/><b>Company is analyzing your idea. Agent work outputs will appear in the cards above.</b></div>}</section>}
  </main>;
}
